export enum PlaceCategory {
  RESTAURANT = 'RESTAURANT',
  CAFE = 'CAFE',
  STREET_FOOD = 'STREET_FOOD',
  FOOD_COURT = 'FOOD_COURT',
  NIGHT_MARKET = 'NIGHT_MARKET',
  BAR = 'BAR',
  ATTRACTION = 'ATTRACTION',
  SHOPPING_MALL = 'SHOPPING_MALL',
  HOTEL = 'HOTEL',
  HOSTEL = 'HOSTEL',
  RESORT = 'RESORT',
  PARK = 'PARK',
  BEACH = 'BEACH',
  HIKING_TRAIL = 'HIKING_TRAIL',
  MUSEUM = 'MUSEUM',
  TEMPLE = 'TEMPLE',
  MOSQUE = 'MOSQUE',
  CHURCH = 'CHURCH',
  VIEWPOINT = 'VIEWPOINT',
  MARKET = 'MARKET',
  ENTERTAINMENT = 'ENTERTAINMENT',
  CONVENIENCE_STORE = 'CONVENIENCE_STORE',
  LIBRARY = 'LIBRARY',
  COWORKING_SPACE = 'COWORKING_SPACE',
  PHARMACY = 'PHARMACY',
  HOSPITAL = 'HOSPITAL',
  CLINIC = 'CLINIC',
  PETROL_STATION = 'PETROL_STATION',
  EV_CHARGER = 'EV_CHARGER',
  PUBLIC_TOILET = 'PUBLIC_TOILET',
  OTHER = 'OTHER',
}

export enum TransportMode {
  WALKING = 'WALKING',
  DRIVING = 'DRIVING',
  MOTORCYCLE = 'MOTORCYCLE',
  GRAB = 'GRAB',
  BUS = 'BUS',
  MRT = 'MRT',
  LRT = 'LRT',
  KTM = 'KTM',
  ETS = 'ETS',
  FLIGHT = 'FLIGHT',
  FERRY = 'FERRY',
  BICYCLE = 'BICYCLE',
}

export enum TripStatus {
  DRAFT = 'DRAFT',
  PLANNED = 'PLANNED',
  ACTIVE = 'ACTIVE',
  COMPLETED = 'COMPLETED',
  CANCELLED = 'CANCELLED',
}

export enum TravelStyle {
  BUDGET = 'BUDGET',
  MID_RANGE = 'MID_RANGE',
  LUXURY = 'LUXURY',
  ADVENTURE = 'ADVENTURE',
  FOODIE = 'FOODIE',
  CULTURAL = 'CULTURAL',
  FAMILY = 'FAMILY',
  SOLO = 'SOLO',
  BACKPACKER = 'BACKPACKER',
}

export enum UserRole {
  USER = 'USER',
  VERIFIED_USER = 'VERIFIED_USER',
  BUSINESS_OWNER = 'BUSINESS_OWNER',
  PREMIUM_USER = 'PREMIUM_USER',
  MODERATOR = 'MODERATOR',
  ADMIN = 'ADMIN',
  SUPER_ADMIN = 'SUPER_ADMIN',
}

export enum SubscriptionPlan {
  FREE = 'FREE',
  PRO = 'PRO',
  ENTERPRISE = 'ENTERPRISE',
}

export enum SubscriptionStatus {
  ACTIVE = 'ACTIVE',
  PAST_DUE = 'PAST_DUE',
  CANCELED = 'CANCELED',
  EXPIRED = 'EXPIRED',
  TRIALING = 'TRIALING',
}

export enum NotificationType {
  SYSTEM = 'SYSTEM',
  FOLLOW = 'FOLLOW',
  LIKE = 'LIKE',
  COMMENT = 'COMMENT',
  TRIP_INVITE = 'TRIP_INVITE',
  ACHIEVEMENT = 'ACHIEVEMENT',
  PROMOTION = 'PROMOTION',
  REMINDER = 'REMINDER',
  REVIEW_REPLY = 'REVIEW_REPLY',
  TRAVEL_ALERT = 'TRAVEL_ALERT',
}

export enum AIRecommendationType {
  FOOD = 'FOOD',
  ATTRACTION = 'ATTRACTION',
  ROUTE = 'ROUTE',
  WEEKEND_PLAN = 'WEEKEND_PLAN',
  FULL_TRIP = 'FULL_TRIP',
  HIDDEN_GEM = 'HIDDEN_GEM',
  TRENDING = 'TRENDING',
  DATING = 'DATING',
}

export enum PhotoModerationStatus {
  PENDING = 'PENDING',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
  FLAGGED = 'FLAGGED',
}

export enum ReviewModerationStatus {
  PENDING = 'PENDING',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
  FLAGGED = 'FLAGGED',
}

export enum BusinessVerificationStatus {
  UNVERIFIED = 'UNVERIFIED',
  PENDING = 'PENDING',
  VERIFIED = 'VERIFIED',
  REJECTED = 'REJECTED',
}

export enum ContentReportReason {
  SPAM = 'SPAM',
  HARASSMENT = 'HARASSMENT',
  INAPPROPRIATE = 'INAPPROPRIATE',
  FAKE = 'FAKE',
  COPYRIGHT = 'COPYRIGHT',
  OTHER = 'OTHER',
}

export enum ContentReportStatus {
  PENDING = 'PENDING',
  REVIEWING = 'REVIEWING',
  RESOLVED = 'RESOLVED',
  DISMISSED = 'DISMISSED',
}

export enum WeekendTravelStyle {
  RELAXED = 'RELAXED',
  ACTIVE = 'ACTIVE',
  FOODIE = 'FOODIE',
  CULTURAL = 'CULTURAL',
  ADVENTURE = 'ADVENTURE',
  ROMANTIC = 'ROMANTIC',
  FAMILY = 'FAMILY',
  PHOTOGRAPHY = 'PHOTOGRAPHY',
}

export enum SpecialPreference {
  HALAL = 'HALAL',
  VEGETARIAN = 'VEGETARIAN',
  VEGAN = 'VEGAN',
  WHEELCHAIR = 'WHEELCHAIR',
  PET_FRIENDLY = 'PET_FRIENDLY',
  CHILD_FRIENDLY = 'CHILD_FRIENDLY',
  BUDGET = 'BUDGET',
  LUXURY = 'LUXURY',
}

export enum StopCategory {
  HOTEL = 'HOTEL',
  BREAKFAST = 'BREAKFAST',
  LUNCH = 'LUNCH',
  DINNER = 'DINNER',
  ATTRACTION = 'ATTRACTION',
  HIDDEN_GEM = 'HIDDEN_GEM',
  SCENIC_SPOT = 'SCENIC_SPOT',
  COFFEE = 'COFFEE',
  PHOTO_SPOT = 'PHOTO_SPOT',
  SHOPPING = 'SHOPPING',
  PARK = 'PARK',
  TEMPLE = 'TEMPLE',
  BEACH = 'BEACH',
  MUSEUM = 'MUSEUM',
  OTHER = 'OTHER',
}

export enum CostCategory {
  FUEL = 'FUEL',
  TOLL = 'TOLL',
  PARKING = 'PARKING',
  HOTEL = 'HOTEL',
  FOOD = 'FOOD',
  TICKET = 'TICKET',
  TRANSPORT = 'TRANSPORT',
  EMERGENCY_BUFFER = 'EMERGENCY_BUFFER',
  MISC = 'MISC',
}

export enum RelationshipStage {
  DATING = 'DATING',
  ENGAGED = 'ENGAGED',
  MARRIED = 'MARRIED',
}

export enum DateType {
  ROMANTIC = 'ROMANTIC',
  ADVENTURE = 'ADVENTURE',
  FOODIE = 'FOODIE',
  CULTURAL = 'CULTURAL',
  RELAXED = 'RELAXED',
  SURPRISE = 'SURPRISE',
}

export enum DateStatus {
  PLANNED = 'PLANNED',
  CONFIRMED = 'CONFIRMED',
  COMPLETED = 'COMPLETED',
  CANCELLED = 'CANCELLED',
}

export enum WalletType {
  PERSONAL = 'PERSONAL',
  COUPLE = 'COUPLE',
  GROUP = 'GROUP',
}

export enum GoalStatus {
  ACTIVE = 'ACTIVE',
  PAUSED = 'PAUSED',
  COMPLETED = 'COMPLETED',
  CANCELLED = 'CANCELLED',
}

export enum ContributionFrequency {
  DAILY = 'DAILY',
  WEEKLY = 'WEEKLY',
  MONTHLY = 'MONTHLY',
  ONE_TIME = 'ONE_TIME',
}

