name: Deploy to Vercel

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      VERCEL_ORG_ID: team_dsFhURJ8wcTyG2q3gQAal5zA
      VERCEL_PROJECT_ID: prj_jnI2cjbE3IBmYush2mzCnNUmh3Kw
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v2
        with:
          version: 9

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --no-frozen-lockfile

      - name: Deploy to Vercel
        working-directory: apps/web
        run: npx vercel --prod --token=${{ secrets.VERCEL_TOKEN }} --yes
